### ISSUE TITLE
The GTEx RNA-Seq expression data

### ISSUE THREAD

**Issue by godisboy** [uci-cbcl/D-GEX#1]
Hello, professor Li. Recently,I am doing a research in this filed.
But,I can't find the the  GTEx RNA-Seq expression data ----GTEx_RNASeq_RPKM_n2921x55993.gctx at GTEx Portal. 
I don,t know if this data---GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct.gz is appropriate?

**Comment by yil8** [comment]
Hi 

Thanks for you interest in your work. The GTEx data we used in our paper is a preliminary version before the official publication of GTEx, and I did not find it on the GTEx portal either. I will talk to our collaborators from Broad to see if I can release that version from my own. If that's not the case, I will work out a new version of this repository that based on the available version of GTEx on the GTEx portal. Please bare with me for a few days and thank you for pointing out this issue.

**Comment by godisboy** [comment]
Hi， professor Li.
Thanks very much for your response！
I would like to see it in a few days.Maybe I can take a longer time to work out a matching version by myself.
And I have another idea---can I use your frame to do a study on the relationship between snps and quantitative characters  and predict the effects of snp gene expression? I will appreciate it very much if 
you can give some advice.

**Comment by yil8** [comment]
Hi,

We can release the GTEx used for training but not through public download. Can you please email me (yil8@uci.edu) your basic information through a academic institute email? We can provide you the way to download the data.
