### ISSUE TITLE
The supplemental file in bioinformatics

### ISSUE THREAD

**Issue by radio1988** [uci-cbcl/D-GEX#2]
Hello, 

The bioinformatics paper of D-GEX has a dead link to the supplemental files. Would it be possible for you to post the supplemental files here or email me a copy? Thanks!

**Comment by yil8** [comment]
You can refer to the bioRxiv version:

http://biorxiv.org/content/biorxiv/suppl/2015/12/15/034421.DC1/034421-1.pdf

**Comment by radio1988** [comment]
Thank you so much! Have a nice day.
