### ISSUE TITLE
Paper Dataset

### ISSUE THREAD

**Issue by FarshidShekari** [uci-cbcl/D-GEX#5]
Hi
I found your dataset in [this ](https://cbcl.ics.uci.edu/public_data/D-GEX/)URL and I downloat thems but after download completed they extension change into .hdf files. can you help me?
thanks.

**Comment by yil8** [comment]
@FarshidShekari Hi, I have never seen this issue before. Can you just change back from .hdf to .gctx?

**Comment by FarshidShekari** [comment]
I do that but when I use cmapPy(1ktools you used in your code is deprecated) that give me error on that's file is not gctx?

**Comment by yil8** [comment]
@FarshidShekari did you use exactly the v1.1 of l1ktools ? I remember they changed their API later.

**Comment by FarshidShekari** [comment]
No, as I said, l1ktools lib is deprecated and I use cmapPy lib as an alternative.

**Comment by yil8** [comment]
@FarshidShekari sorry, I did not pay enough attention. I would still recommend using l1ktools v1.1 (https://github.com/cmap/l1ktools/releases/tag/v1.1), since I've only tested on this one. I not quite familiar with cmapPy.
