### ISSUE TITLE
Same genes in landmark set and target set

### ISSUE THREAD

**Issue by lucananni93** [uci-cbcl/D-GEX#7]
Hi, 

I am a PhD student at Polytechnic University of Milan and I am interested in the D-GEX work, of which you are one of the authors.
I would like to ask how did you extract the two lists of landmark and target genes `map_lm.txt` and `map_tg.txt` in the Github repository.

I am noticing that a subset of the landmark genes (more or less 400 genes) is also part of the set of target genes (but considering different probes). What is the reason behind this?

Thank you in advance.

**Comment by yil8** [comment]
@lucananni93 Hi, `map_lm.txt` and `map_tg.txt` were selected and provided by the original authors of  the LINCS program. They used to have a website that you can checkout, unfortunately, the website is not accessible anymore.
