### ISSUE TITLE
Is  GTEx_RNASeq_RPKM_n2921x55993.gctx now available?

### ISSUE THREAD

**Issue by yezhengli-Mr9** [uci-cbcl/D-GEX#8]
Hi Sir,
is  GTEx_RNASeq_RPKM_n2921x55993.gctx now available?

**Comment by yezhengli-Mr9** [comment]
I think a description of GTEx input is also fine. I can use update GTEx data anyway.

**Comment by yil8** [comment]
@yezhengli-Mr9 I've replied your email, please check it out

**Comment by yezhengli-Mr9** [comment]
Get it, thanks a lot! You are still active~
